### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

### ISSUE THREAD

**Issue by cmug81** [edds/jenkins-dashboard#2]
Hi,

I get an error when using Chrome 49.0.2623.87 (64-bit).
Error message reads:
XMLHttpRequest cannot load http://<hostname>:8080//api/json?tree=views[name,jobs[name…fulBuild[duration],healthReport[description,score],inQueue,buildable,color]]. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 403.

**Comment by cmug81** [comment]
same behavior if I run this with file:/// or through python -m SimpleHTTPServer or via a separate Apache server

**Comment by edds** [comment]
You need to ensure that your jenkins server is setup to handle CORS requests.

**Comment by Cka3** [comment]
How? Especially on windows
